[meta]
description = "The most exquisite Elixir conference in Portugal"
date = "14 & 15 May 2021"

[location]
city = "Braga, Portugal"

[tickets]
url = "https://ti.to/subvisual/alchemy-conf-2021"

[tickets.early_bird]
date = "01-01-2021"
price = "160.80€"
